name: Build Android with EAS

on:
  push:
    branches:
      - feature/deploy-monitoring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Build Android
        run: eas build --platform android --non-interactive --profile preview
